/// Pays proposés pour les préférences (onboarding + réglages).
class AppCountryOption {
  const AppCountryOption({
    required this.code,
    required this.labelFr,
    required this.labelEn,
  });

  final String code;
  final String labelFr;
  final String labelEn;
}

const List<AppCountryOption> kAppCountryOptions = [
  AppCountryOption(code: 'FR', labelFr: 'France', labelEn: 'France'),
  // Afrique (ordre alphabétique FR)
  AppCountryOption(code: 'ZA', labelFr: 'Afrique du Sud', labelEn: 'South Africa'),
  AppCountryOption(code: 'DZ', labelFr: 'Algérie', labelEn: 'Algeria'),
  AppCountryOption(code: 'BJ', labelFr: 'Bénin', labelEn: 'Benin'),
  AppCountryOption(code: 'BW', labelFr: 'Botswana', labelEn: 'Botswana'),
  AppCountryOption(code: 'BF', labelFr: 'Burkina Faso', labelEn: 'Burkina Faso'),
  AppCountryOption(code: 'BI', labelFr: 'Burundi', labelEn: 'Burundi'),
  AppCountryOption(code: 'CM', labelFr: 'Cameroun', labelEn: 'Cameroon'),
  AppCountryOption(code: 'CV', labelFr: 'Cap-Vert', labelEn: 'Cape Verde'),
  AppCountryOption(code: 'CF', labelFr: 'Centrafrique', labelEn: 'Central African Republic'),
  AppCountryOption(code: 'KM', labelFr: 'Comores', labelEn: 'Comoros'),
  AppCountryOption(code: 'CG', labelFr: 'Congo', labelEn: 'Congo'),
  AppCountryOption(code: 'CD', labelFr: 'Congo (RDC)', labelEn: 'DR Congo'),
  AppCountryOption(code: 'CI', labelFr: "Côte d'Ivoire", labelEn: "Côte d'Ivoire"),
  AppCountryOption(code: 'DJ', labelFr: 'Djibouti', labelEn: 'Djibouti'),
  AppCountryOption(code: 'EG', labelFr: 'Égypte', labelEn: 'Egypt'),
  AppCountryOption(code: 'ET', labelFr: 'Éthiopie', labelEn: 'Ethiopia'),
  AppCountryOption(code: 'GA', labelFr: 'Gabon', labelEn: 'Gabon'),
  AppCountryOption(code: 'GM', labelFr: 'Gambie', labelEn: 'Gambia'),
  AppCountryOption(code: 'GH', labelFr: 'Ghana', labelEn: 'Ghana'),
  AppCountryOption(code: 'GN', labelFr: 'Guinée', labelEn: 'Guinea'),
  AppCountryOption(code: 'GW', labelFr: 'Guinée-Bissau', labelEn: 'Guinea-Bissau'),
  AppCountryOption(code: 'GQ', labelFr: 'Guinée équatoriale', labelEn: 'Equatorial Guinea'),
  AppCountryOption(code: 'KE', labelFr: 'Kenya', labelEn: 'Kenya'),
  AppCountryOption(code: 'LS', labelFr: 'Lesotho', labelEn: 'Lesotho'),
  AppCountryOption(code: 'LR', labelFr: 'Liberia', labelEn: 'Liberia'),
  AppCountryOption(code: 'LY', labelFr: 'Libye', labelEn: 'Libya'),
  AppCountryOption(code: 'MG', labelFr: 'Madagascar', labelEn: 'Madagascar'),
  AppCountryOption(code: 'MW', labelFr: 'Malawi', labelEn: 'Malawi'),
  AppCountryOption(code: 'ML', labelFr: 'Mali', labelEn: 'Mali'),
  AppCountryOption(code: 'MA', labelFr: 'Maroc', labelEn: 'Morocco'),
  AppCountryOption(code: 'MU', labelFr: 'Maurice', labelEn: 'Mauritius'),
  AppCountryOption(code: 'MR', labelFr: 'Mauritanie', labelEn: 'Mauritania'),
  AppCountryOption(code: 'MZ', labelFr: 'Mozambique', labelEn: 'Mozambique'),
  AppCountryOption(code: 'NA', labelFr: 'Namibie', labelEn: 'Namibia'),
  AppCountryOption(code: 'NE', labelFr: 'Niger', labelEn: 'Niger'),
  AppCountryOption(code: 'NG', labelFr: 'Nigeria', labelEn: 'Nigeria'),
  AppCountryOption(code: 'UG', labelFr: 'Ouganda', labelEn: 'Uganda'),
  AppCountryOption(code: 'RW', labelFr: 'Rwanda', labelEn: 'Rwanda'),
  AppCountryOption(code: 'ST', labelFr: 'São Tomé-et-Príncipe', labelEn: 'São Tomé and Príncipe'),
  AppCountryOption(code: 'SN', labelFr: 'Sénégal', labelEn: 'Senegal'),
  AppCountryOption(code: 'SC', labelFr: 'Seychelles', labelEn: 'Seychelles'),
  AppCountryOption(code: 'SL', labelFr: 'Sierra Leone', labelEn: 'Sierra Leone'),
  AppCountryOption(code: 'SO', labelFr: 'Somalie', labelEn: 'Somalia'),
  AppCountryOption(code: 'SD', labelFr: 'Soudan', labelEn: 'Sudan'),
  AppCountryOption(code: 'SS', labelFr: 'Soudan du Sud', labelEn: 'South Sudan'),
  AppCountryOption(code: 'SZ', labelFr: 'Eswatini', labelEn: 'Eswatini'),
  AppCountryOption(code: 'TZ', labelFr: 'Tanzanie', labelEn: 'Tanzania'),
  AppCountryOption(code: 'TD', labelFr: 'Tchad', labelEn: 'Chad'),
  AppCountryOption(code: 'TG', labelFr: 'Togo', labelEn: 'Togo'),
  AppCountryOption(code: 'TN', labelFr: 'Tunisie', labelEn: 'Tunisia'),
  AppCountryOption(code: 'ZM', labelFr: 'Zambie', labelEn: 'Zambia'),
  AppCountryOption(code: 'ZW', labelFr: 'Zimbabwe', labelEn: 'Zimbabwe'),
  AppCountryOption(code: 'BE', labelFr: 'Belgique', labelEn: 'Belgium'),
  AppCountryOption(code: 'CH', labelFr: 'Suisse', labelEn: 'Switzerland'),
  AppCountryOption(code: 'LU', labelFr: 'Luxembourg', labelEn: 'Luxembourg'),
  AppCountryOption(code: 'CA', labelFr: 'Canada', labelEn: 'Canada'),
  AppCountryOption(code: 'DE', labelFr: 'Allemagne', labelEn: 'Germany'),
  AppCountryOption(code: 'ES', labelFr: 'Espagne', labelEn: 'Spain'),
  AppCountryOption(code: 'IT', labelFr: 'Italie', labelEn: 'Italy'),
  AppCountryOption(code: 'GB', labelFr: 'Royaume-Uni', labelEn: 'United Kingdom'),
  AppCountryOption(code: 'US', labelFr: 'États-Unis', labelEn: 'United States'),
];
